### PR TITLE
Update CPP11.md

### PR DESCRIPTION
**Pull request by dimalosev0605**
semicolons absence

### CODE REVIEW

**Review by patrickleungwl — COMMENTED** [review]
These look like good changes.  This commit should be approved.

**Comment by AnthonyCalandra** [comment]
Sorry for the PR spam, can you also make the changes to README.md as well? My github action isn't working properly unfortunately.

**Comment by dimalosev0605** [comment]
> Sorry for the PR spam, can you also make the changes to README.md as well? My github action isn't working properly unfortunately.

Done!

**Comment by AnthonyCalandra** [comment]
LGTM, thanks!

**Pull request merged**
